FROM python:3.13-alpine AS builder
WORKDIR /app

RUN apk add --no-cache gcc musl-dev libffi-dev

COPY requirements.txt .
RUN pip install --no-cache-dir --prefix=/install -r requirements.txt

COPY . .

# ---- runtime ----
FROM python:3.13-alpine 
WORKDIR /app

COPY --from=builder /install /usr/local
COPY --from=builder /app /app



CMD ["python3", "-m", "gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "app:app"]
